"""Artifact creation: charts (via sandbox Runner) and reports (markdown→HTML→PDF).

This module provides:

* :class:`ArtifactRecord` — metadata for an artifact (kind, file path, mime).
* :func:`run_chart_script` — writes a Python chart script to the workspace
  and executes it via the :class:`Runner` (bwrap in production, FakeRunner
  in tests). Returns an :class:`ArtifactRecord`.
* :func:`markdown_to_html` — converts markdown to HTML using the
  ``markdown`` package.
* :func:`html_to_pdf` — converts HTML/text to PDF bytes using
  ``reportlab`` (lazy import — not required for tests).
* :func:`create_report` — generates a full report (markdown → HTML → PDF)
  and stores it as an artifact in the workspace.
* :class:`ArtifactService` — high-level service that wraps the above and
  stores artifact records in the :class:`Store`.

Design notes:
* All file I/O is confined to the per-thread workspace.
* The Runner is injectable: production uses :class:`BwrapRunner`, tests
  use :class:`FakeRunner`.
* ``reportlab`` is imported lazily inside ``html_to_pdf`` so the test
  suite runs green even without it installed (the PDF test is
  ``skipif`` when reportlab is absent).
* Charts are generated by running a Python script in the sandbox that
  produces a PNG. The script is written to the workspace first.
"""

from __future__ import annotations

import mimetypes
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Artifact record
# ---------------------------------------------------------------------------


@dataclass
class ArtifactRecord:
    """Metadata for a single artifact file.

    Attributes
    ----------
    filename:
        The file name within the workspace (e.g. ``chart.png``).
    path:
        Full workspace path to the artifact.
    kind:
        One of: ``"chart"``, ``"report"``, ``"image"``, ``"code"``.
    mime:
        MIME type (e.g. ``"image/png"``, ``"text/html"``, ``"application/pdf"``).
    thread_id:
        The thread this artifact belongs to.
    message_index:
        Index of the message that produced this artifact.
    created:
        Timestamp (UTC).
    size_bytes:
        File size (0 if unknown / fake).
    _id:
        The store-assigned id, set once the record has been persisted (via
        :class:`ArtifactService`/:class:`~pengyplexity.core.images.ImageService`).
        ``None`` until then.
    """

    filename: str
    path: Path
    kind: str
    mime: str
    thread_id: str = ""
    message_index: int = 0
    created: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    size_bytes: int = 0
    _id: Optional[str] = None
    # The sandbox run that produced this artifact, when there was one (charts).
    # Kept off :meth:`to_dict` — it is diagnostic state for the tool result,
    # not something to persist.
    run_result: Any = None

    def to_dict(self) -> Dict[str, Any]:
        """As a dict for storage."""
        return {
            "filename": self.filename,
            "path": str(self.path),
            "kind": self.kind,
            "mime": self.mime,
            "thread_id": self.thread_id,
            "message_index": self.message_index,
            "created": self.created,
            "size_bytes": self.size_bytes,
        }


# ---------------------------------------------------------------------------
# Chart generation (via Runner)
# ---------------------------------------------------------------------------


def run_chart_script(
    script: str,
    workspace: Path,
    runner,
    output_filename: str = "chart.png",
    thread_id: str = "",
    message_index: int = 0,
    cancel=None,
) -> ArtifactRecord:
    """Write a chart script to the workspace and run it via the Runner.

    Parameters
    ----------
    script:
        The Python script content (typically uses matplotlib to save a PNG).
    workspace:
        The per-thread workspace root.
    runner:
        A :class:`Runner` instance (BwrapRunner or FakeRunner).
    output_filename:
        Expected output file name in the workspace.
    thread_id, message_index:
        For the artifact record.
    cancel:
        Optional :class:`~pengyplexity.core.cancel.CancelToken` for the turn,
        so pressing Stop kills a long-running chart script immediately.

    Returns
    -------
    ArtifactRecord
        With the path to the (expected) output file.
    """
    # Write the script to the workspace's scratch dir — not `chart_script.py`
    # in the root, which overwrote any file of that name and left itself
    # behind in the user's artifact listing.
    from .toolexec import SCRATCH_DIR, scratch_path

    script_path = scratch_path(workspace, "chart.py")
    script_path.write_text(script, encoding="utf-8")

    # Execute via the runner (sandboxed in production, fake in tests).
    try:
        result = runner.run(
            f"python3 {SCRATCH_DIR}/{script_path.name}", workspace, cancel=cancel
        )
    finally:
        script_path.unlink(missing_ok=True)

    # The output file should be in the workspace. A model that writes an
    # absolute or traversing filename is rejected here rather than writing
    # outside the sandbox.
    from ..sandbox import confine

    output_path = confine.resolve(workspace, output_filename)
    # In production, the file exists; in tests (FakeRunner) it may not.
    size = output_path.stat().st_size if output_path.exists() else 0

    return ArtifactRecord(
        filename=output_path.name,
        path=output_path,
        kind="chart",
        mime="image/png",
        thread_id=thread_id,
        message_index=message_index,
        size_bytes=size,
        # Carried so a failed chart can report what the interpreter said
        # (usually a traceback) instead of a generic "it didn't work".
        run_result=result,
    )


# ---------------------------------------------------------------------------
# Report: markdown → HTML → PDF
# ---------------------------------------------------------------------------


def markdown_to_html(markdown_text: str) -> str:
    """Convert markdown to HTML using the ``markdown`` package."""
    import markdown

    return markdown.markdown(markdown_text, extensions=["tables", "fenced_code"])


def html_to_pdf(html_or_text: str) -> bytes:
    """Render Markdown report text to PDF bytes using ``reportlab``.

    Callers pass the report's **Markdown** (that is what ``create_report``
    has). The previous version split it on blank lines and emitted each block
    as one paragraph, so every ``**bold**``, ``- bullet``, ``1.`` and
    ``| table |`` reached the page as literal syntax — the PDF was markdown
    source in a serif font. This walks the Markdown instead and maps it onto
    reportlab flowables: headings, bulleted and numbered lists, block quotes,
    fenced code, tables, and inline bold/italic/code/links.

    Raises
    ------
    ImportError
        If ``reportlab`` is not installed.
    """
    from io import BytesIO

    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        ListFlowable,
        ListItem,
        Paragraph,
        Preformatted,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    styles = getSampleStyleSheet()
    code_style = ParagraphStyle(
        "PengyCode",
        parent=styles["Code"],
        fontSize=8,
        leading=10,
        leftIndent=12,
        backColor=colors.whitesmoke,
    )
    quote_style = ParagraphStyle(
        "PengyQuote",
        parent=styles["BodyText"],
        leftIndent=18,
        textColor=colors.HexColor("#444444"),
        borderPadding=2,
    )
    cell_style = ParagraphStyle(
        "PengyCell", parent=styles["BodyText"], fontSize=9, leading=11, alignment=TA_LEFT
    )
    head_cell_style = ParagraphStyle(
        "PengyHeadCell", parent=cell_style, fontName="Helvetica-Bold"
    )

    story: List[Any] = []
    lines = (html_or_text or "").replace("\r\n", "\n").split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # Fenced code block.
        if stripped.startswith("```"):
            i += 1
            block = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1  # closing fence
            story.append(Preformatted("\n".join(block), code_style))
            story.append(Spacer(1, 6))
            continue

        # Table: a header row followed by a |---|---| separator.
        if "|" in stripped and i + 1 < len(lines) and _is_table_rule(lines[i + 1]):
            header = _split_row(stripped)
            i += 2
            rows = []
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                rows.append(_split_row(lines[i]))
                i += 1
            width = max([len(header)] + [len(r) for r in rows]) or 1
            data = [
                [Paragraph(_inline_to_rl(c), head_cell_style) for c in _pad(header, width)]
            ] + [
                [Paragraph(_inline_to_rl(c), cell_style) for c in _pad(r, width)]
                for r in rows
            ]
            table = Table(data, hAlign="LEFT")
            table.setStyle(
                TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#BBBBBB")),
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFEFEF")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 4),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(table)
            story.append(Spacer(1, 8))
            continue

        # Heading.
        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            level = min(len(heading.group(1)), 4)
            story.append(
                Paragraph(_inline_to_rl(heading.group(2)), styles[f"Heading{level}"])
            )
            i += 1
            continue

        # Horizontal rule.
        if re.fullmatch(r"(\*\s*){3,}|(-\s*){3,}|(_\s*){3,}", stripped):
            story.append(Spacer(1, 10))
            i += 1
            continue

        # Bulleted or numbered list (consecutive items of the same kind).
        bullet = re.match(r"^\s*[-*+]\s+(.*)$", line)
        numbered = re.match(r"^\s*\d+[.)]\s+(.*)$", line)
        if bullet or numbered:
            ordered = numbered is not None
            items = []
            while i < len(lines):
                m = (
                    re.match(r"^\s*\d+[.)]\s+(.*)$", lines[i])
                    if ordered
                    else re.match(r"^\s*[-*+]\s+(.*)$", lines[i])
                )
                if not m:
                    break
                items.append(
                    ListItem(Paragraph(_inline_to_rl(m.group(1)), styles["BodyText"]))
                )
                i += 1
            story.append(
                ListFlowable(
                    items,
                    bulletType="1" if ordered else "bullet",
                    start="1" if ordered else None,
                    leftIndent=18,
                )
            )
            story.append(Spacer(1, 6))
            continue

        # Block quote.
        if stripped.startswith(">"):
            quoted = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quoted.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            story.append(Paragraph(_inline_to_rl(" ".join(quoted)), quote_style))
            story.append(Spacer(1, 6))
            continue

        # Plain paragraph: join until a blank line or a new block starts.
        para = []
        while i < len(lines) and lines[i].strip() and not _starts_block(lines[i]):
            para.append(lines[i].strip())
            i += 1
        story.append(Paragraph(_inline_to_rl(" ".join(para)), styles["BodyText"]))
        story.append(Spacer(1, 4))

    if not story:
        story.append(Spacer(1, 1))

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )
    doc.build(story)
    return buffer.getvalue()


def _starts_block(line: str) -> bool:
    """True if *line* begins a Markdown block rather than continuing a paragraph."""
    stripped = line.strip()
    return bool(
        stripped.startswith(("#", ">", "```"))
        or re.match(r"^\s*[-*+]\s+", line)
        or re.match(r"^\s*\d+[.)]\s+", line)
        or ("|" in stripped and stripped.count("|") >= 2)
    )


def _is_table_rule(line: str) -> bool:
    """True for a Markdown table's ``|---|:--:|`` separator row."""
    stripped = line.strip()
    return bool(stripped) and bool(re.fullmatch(r"\|?[\s:|-]+\|?", stripped)) and "-" in stripped


def _split_row(line: str) -> List[str]:
    """Split one Markdown table row into its cells."""
    return [c.strip() for c in line.strip().strip("|").split("|")]


def _pad(cells: List[str], width: int) -> List[str]:
    return list(cells) + [""] * (width - len(cells))


def _inline_to_rl(text: str) -> str:
    """Convert inline Markdown to the mini-HTML reportlab's Paragraph accepts.

    Everything is XML-escaped first, so report text can never inject markup
    into the PDF; only the tags produced here are live.
    """
    out = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Code spans are parked so their contents are not re-parsed as markup.
    spans: List[str] = []

    def _park(match: "re.Match[str]") -> str:
        spans.append(match.group(1))
        return f"\x00{len(spans) - 1}\x00"

    out = re.sub(r"`([^`]+)`", _park, out)
    out = re.sub(r"!\[([^\]]*)\]\(([^)\s]+)\)", r"\1", out)  # images: alt text only
    out = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r'<link href="\2">\1</link>', out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    out = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", out)
    out = re.sub(r"(?<!_)__([^_]+)__(?!_)", r"<b>\1</b>", out)
    out = re.sub(r"~~([^~]+)~~", r"<strike>\1</strike>", out)
    out = re.sub(
        r"\x00(\d+)\x00",
        lambda m: f'<font face="Courier">{spans[int(m.group(1))]}</font>',
        out,
    )
    return out


def create_report(
    markdown_text: str,
    workspace: Path,
    title: str = "Report",
    thread_id: str = "",
    message_index: int = 0,
) -> Dict[str, ArtifactRecord]:
    """Create a report artifact: markdown → HTML file + PDF file.

    Returns
    -------
    dict
        ``{"html": ArtifactRecord, "pdf": ArtifactRecord}`` — or just
        ``{"html": ...}`` if reportlab is not available.
    """
    # HTML version.
    html_content = markdown_to_html(markdown_text)
    html_path = workspace / f"{_safe_filename(title)}.html"
    html_path.write_text(html_content, encoding="utf-8")
    html_artifact = ArtifactRecord(
        filename=html_path.name,
        path=html_path,
        kind="report",
        mime="text/html",
        thread_id=thread_id,
        message_index=message_index,
        size_bytes=html_path.stat().st_size,
    )

    artifacts = {"html": html_artifact}

    # PDF version (if reportlab is available).
    try:
        pdf_bytes = html_to_pdf(markdown_text)
        pdf_path = workspace / f"{_safe_filename(title)}.pdf"
        pdf_path.write_bytes(pdf_bytes)
        pdf_artifact = ArtifactRecord(
            filename=pdf_path.name,
            path=pdf_path,
            kind="report",
            mime="application/pdf",
            thread_id=thread_id,
            message_index=message_index,
            size_bytes=len(pdf_bytes),
        )
        artifacts["pdf"] = pdf_artifact
    except ImportError:
        pass  # reportlab not available — HTML only.

    return artifacts


# ---------------------------------------------------------------------------
# ArtifactService — high-level store integration
# ---------------------------------------------------------------------------


class ArtifactService:
    """High-level service for creating and storing artifacts.

    Parameters
    ----------
    store:
        A :class:`Store` (or compatible object) with artifact methods.
    runner:
        A :class:`Runner` for sandboxed execution.
    """

    def __init__(self, store, runner) -> None:
        self.store = store
        self.runner = runner

    def create_chart(
        self,
        workspace: Path,
        script: str,
        thread_id: str,
        message_index: int = 0,
        output_filename: str = "chart.png",
        cancel=None,
    ) -> ArtifactRecord:
        """Generate a chart in the sandbox and store the artifact record."""
        record = run_chart_script(
            script=script,
            workspace=workspace,
            runner=self.runner,
            output_filename=output_filename,
            thread_id=thread_id,
            message_index=message_index,
            cancel=cancel,
        )
        # Store in the artifacts collection (if the store supports it).
        if hasattr(self.store, "create_artifact"):
            stored = self.store.create_artifact(record.to_dict())
            if stored:
                record._id = stored.get("_id")
        return record

    def create_report(
        self,
        workspace: Path,
        markdown_text: str,
        thread_id: str,
        title: str = "Report",
        message_index: int = 0,
    ) -> Dict[str, ArtifactRecord]:
        """Generate a report (HTML + PDF) and store artifact records."""
        artifacts = create_report(
            markdown_text=markdown_text,
            workspace=workspace,
            title=title,
            thread_id=thread_id,
            message_index=message_index,
        )
        for record in artifacts.values():
            if hasattr(self.store, "create_artifact"):
                stored = self.store.create_artifact(record.to_dict())
                if stored:
                    record._id = stored.get("_id")
        return artifacts


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_filename(title: str) -> str:
    """Sanitize a title into a safe file name stem."""
    name = title.lower().replace(" ", "_").replace("/", "_")
    # Remove anything that's not alphanumeric, underscore, or hyphen.
    name = "".join(c for c in name if c.isalnum() or c in ("_", "-"))
    return name[:50] or "report"
